version: '3.9'

services:
  postgres:
    image: postgres
    container_name: ${CONTAINER_NAME}
    ports:
      - "5433:5432"
    environment:
      - DATABESE_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}